# Generated by Django 4.1.4 on 2022-12-13 21:16

import api.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sku', models.IntegerField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'В наличии'), (2, 'Под заказ'), (3, 'Ожидается поступление'), (4, 'Нет в наличии'), (5, 'Не производится')])),
                ('image', api.fields.WEBPField(upload_to='media/images/product')),
            ],
        ),
    ]
