# Generated by Django 4.1.4 on 2022-12-14 11:43

import api.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=api.fields.WEBPField(upload_to='media/images/product'),
        ),
    ]
